
<div id="main-search">
	<h2><a href="">Login</a></h2>
	<div class='message msg-login'></div>

	<div id='loginForm'>
		<?php 
		if($this->message !== null) {
			echo "<div class='message'>{$this->message}</div><br /><br />";
		}
		?>

		<?php echo $this->form; ?>
		
		<p>Don't have an account? &nbsp; <a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'add'), 'default', true); ?>">Sign Up</a> 
		&nbsp; | &nbsp; <a href="<?php echo $this->url(array(
			'controller'=>'auth',
			'action'=>'reset',
			'module'=>'default',), 'default', true); ?>">I Forgot Password</a></p>
	</div>
</div>