<div id="main-search">
 <h2>An error occurred</h2> 
  <h3><?= $this->message ?></h3> 

  <? if ('development' == APPLICATION_ENV): ?> 
  
  <h3>Exception information:</h3> 
  <p> 
      <b>Message:</b> <?= $this->exception->getMessage() ?> 
  </p> 

  <h3>Stack trace:</h3> 
  <pre><?= $this->exception->getTraceAsString() ?> 
  </pre> 

  <h3>Request Parameters:</h3> 
  <pre><? var_dump($this->request->getParams()) ?> 
  </pre> 
  <? endif ?>
  </div>
            