<div id="main-search">
<h2><a href="#">About</a></h2>

<dl>
	<dt>What is vacantDC!</dt>
	<dd>vacantDC! is a portal of vacant properties in Washington, DC</dd>
	<br />
	<dt>I think there are missing properties and properties that are on your vacant list that aren't vacant.</dt>
	<dd>That's probably correct!  The application is still in development.  Please give us some time.</dd>
	<br />
	<dt>I still have more questions!</dt>
	<dd>Send me some email at <a href="mailto:questions@vacantdc.com">questions@vacantdc</a></dd>
</dl>
</div>