<p style="text-align:right;">
	
	<a href="<?php echo $this->url(array(
		'controller' => 'index',
		'action' => 'index',
		'module' => 'default'), '', true); ?>">VacantDC!</a> - 
		
	<a href="http://www.appsfordemocracy.org/">Apps for Democracy</a> - 
	<a href="mailto:questions@vacantdc.com">questions@vacantdc.com</a>
<br /><br />
<a rel="license" 
href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/"><img 
alt="Creative Commons License" style="border-width:0" 
src="http://i.creativecommons.org/l/by-nc-sa/3.0/us/80x15.png" /></a><br 
/><span xmlns:dc="http://purl.org/dc/elements/1.1/" 
href="http://purl.org/dc/dcmitype/InteractiveResource" property="dc:title" 
rel="dc:type">vacantDC!</span> by <a 
xmlns:cc="http://creativecommons.org/ns#" href="http://www.vacantdc.com/" 
property="cc:attributionName" rel="cc:attributionURL">vacantDC!</a> is 
licensed under a <a rel="license" 
href="http://creativecommons.org/licenses/by-nc-sa/3.0/us/">Creative 
Commons Attribution-Noncommercial-Share Alike 3.0 United States 
License</a>.<br />Based on a work at <a 
xmlns:dc="http://purl.org/dc/elements/1.1/" 
href="http://code.google.com/p/vacantdc/" 
rel="dc:source">code.google.com</a>.<br />Permissions beyond the scope of 
this license may be available at <a 
xmlns:cc="http://creativecommons.org/ns#" href="http://www.vacantdc.com/" 
rel="cc:morePermissions">http://www.vacantdc.com/</a>. </p>
