<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity()) {
	$identity = $auth->getIdentity();
}
?>

<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/style.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/example.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/lightbox.css'); ?>
    <?php echo $this->headScript()->appendFile('/javascript/tabber.js', 'text/javascript'); ?>
    <?php echo $this->headScript()->appendFile('/javascript/lightbox.js', 'text/javascript'); ?>
</head> 
<body>
	<div id="content">
				<h1><span class="hr">vacant</span>DC!</h1>

		<ul id="top">
			<?php echo $this->partial('_topNavLinks.phtml', $identity); ?>
		</ul>
		
    	<?php echo $this->layout()->content; ?> 
	 
		<div id="footer">
			<?php echo $this->partial('_footer.phtml'); ?>
		</div>

	</div>

<script type="text/javascript">
  var uservoiceJsHost = ("https:" == document.location.protocol) ? 
"https://uservoice.com" : "http://cdn.uservoice.com";
  document.write(unescape("%3Cscript src='" + uservoiceJsHost + 
"/javascripts/widgets/tab.js' type='text/javascript'%3E%3C/script%3E"))
</script>
<script type="text/javascript">
UserVoice.Tab.show({ 
  key: 'vacantdc',
  host: 'vacantdc.uservoice.com', 
  forum: 'general', 
  alignment: 'left',
  background_color:'#f00', 
  text_color: 'white',
  hover_color: '#06C',
  lang: 'en'
})
</script>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." 
: "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + 
"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-60313-14");
pageTracker._trackPageview();
} catch(err) {}</script>

</body>
</html>
